[build]
builder = "nixpacks"

[deploy]
startCommand = "node backend/server.js"

[env]
NODE_ENV = "production"
MONGO_URI = "mongodb+srv://lonergamers:EstB999Jw@clustersamwrld.hqnhrry.mongodb.net/Sam-WRLD?retryWrites=true&w=majority&appName=ClusterSamWRLD"
DB_NAME = "Sam-WRLD"
COLLECTION_NAME = "files"
INIT_SAMPLE_DATA = "true"