[build]
builder = "nixpacks"

[deploy]
startCommand = "node backend/server.js"  # ✅ <-- run using Node
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
NODE_ENV = "production"
